lifecycle_manager_navigation:
  ros__parameters:
    autostart: false
    node_names:
      - "controller_server"
      - "planner_server"
      - "waypoint_follower"
      - "bt_navigator"
    bond_timeout: 4.0
    attempt_respawn_reconnection: true
    bond_respawn_max_duration: 10.0
