# https://github.com/cra-ros-pkg/robot_localization/blob/humble-devel/params/ekf.yaml

ekf_filter:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    transform_time_offset: 0.0
    transform_timeout: 0.0
    print_diagnostics: true
    debug: false
    permit_corrected_publication: false
    publish_acceleration: false
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom

    odom0: odom
    odom0_config: [true,  true,  true,
                       false, false, false,
                       false, false, false,
                       false, false, true,
                       false, false, false]
    #odom0_config: [false, false, false,
    #                false, false, false,
    #                true,  false, false,
    #                false, false, true,
    #                false, false, false]
    odom0_queue_size: 3
    odom0_rejection_threshold: 15.0
    odom0_nodelay: false
    
    #imu0: oak/imu
    #imu0_config: [false, false, false,
    #              false, false, false,
    #              false, false, false,
    #              true, true, true,
    #              false, false, false]
    #imu0_nodelay: false
    #imu0_differential: false
    #imu0_relative: true
    #imu0_queue_size: 5
    #imu0_pose_rejection_threshold: 15.0
    #imu0_twist_rejection_threshold: 15.0
    #imu0_linear_acceleration_rejection_threshold: 15.0
    #imu0_remove_gravitational_acceleration: true
