oak:
  oak_wrapper:
    ros__parameters:
      depth:
        min_distance: 0.0
        max_distance: 3.0
        confidence_threshold: 30
        lr_check_enabled: true
        lr_check_threshold: 1
        subpixel_enabled: true
        subpixel_fractional_bits: 3
