/oak:
  ros__parameters:
    camera:
      i_nn_type: none
      i_laser_dot_brightness: 1200
    imu:
      i_acc_freq: 50
      i_rot_freq: 50
      i_gyro_freq: 50
    #TODO adjust fps for UpBoard
    rgb:
      i_fps: 5.0
      i_sensor_img_orientation: ROTATE_180_DEG
    left:
      i_publish_topic: false
      i_fps: 5.0
      #i_sensor_img_orientation: ROTATE_180_DEG
    right:  
      i_publish_topic: true
      i_fps: 5.0
      #i_sensor_img_orientation: ROTATE_180_DEG
    stereo:
      i_align_depth: false #if true for some reason changes the frame of the pointcloud
      i_subpixel: true
      i_stereo_conf_threshold: 110 #most important parameter
      i_enable_brightness_filter: true
      i_brightness_filter_min_brightness: 1
      i_brightness_filter_max_brightness: 225
      i_enable_decimation_filter: true
      #i_lrc_threshold: 5