/oak:
  ros__parameters:
    camera:
      i_nn_type: none
      i_laser_dot_brightness: 1000
    imu:
      i_acc_freq: 50
      i_rot_freq: 50
      i_gyro_freq: 50
    #TODO adjust fps for UpBoard
    rgb:
      i_fps: 10.0
      i_sensor_img_orientation: ROTATE_180_DEG
      i_resolution: '720P'
    left:
      i_publish_topic: false
      i_fps: 10.0
      #i_sensor_img_orientation: ROTATE_180_DEG
    right:  
      i_publish_topic: false
      i_fps: 10.0
      #i_sensor_img_orientation: ROTATE_180_DEG
    stereo:
      i_align_depth: true
      i_subpixel: true
      i_stereo_conf_threshold: 110 #most important parameter
      i_enable_brightness_filter: false
      i_brightness_filter_min_brightness: 1
      i_brightness_filter_max_brightness: 225
      i_enable_decimation_filter: true
      i_publish_right_rect: true
      #i_lrc_threshold: 5

#/oak:
#  ros__parameters:
#    camera:
#      i_nn_type: none
#    rgb:
#      i_resolution: '720P'
#    stereo:
#      i_align_depth: true
#      i_subpixel: true
#      i_publish_right_rect: true