/oak:
  ros__parameters:
    depth:
      confidence_threshold: 50
      lr_check_enabled: true
      lr_check_threshold: 5
      subpixel_enabled: true
      subpixel_fractional_bits: 3
      min_distance: 0.0
      max_distance: 10.0
